/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_heydenaldana_22111098;

import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heyde
 */
public class jPartida extends javax.swing.JFrame {

    private HiloTabla t;
    private HiloLabel l;
    private BDD bdd;
    private jmenuprincipal jmp = new jmenuprincipal();
    
    /**
     * Creates new form jPartida
     */
    public jPartida() {
        initComponents();
        JLabel l[] = {jjugador, jestrella, jdistanciar, jdistanciat};
        t = new HiloTabla(jtabla, jpbdistancia, l);
        jpartida.setText(jmp._partida);
        // rellenar comboboes
        try
        {
            bdd.rellenacbjugadores(cbplayer);
            bdd.rellenacbestrella(cbstar);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "ADVERTENCIA: Es posible que el programa no funcione correctamente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jpbdistancia = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        bcomenzar = new javax.swing.JButton();
        bpausa = new javax.swing.JButton();
        bagregar = new javax.swing.JButton();
        cbplayer = new javax.swing.JComboBox<>();
        cbstar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jpartida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jjugador = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jestrella = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdistanciar = new javax.swing.JLabel();
        jdistanciat = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jmensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("P A R T I D A S");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jpbdistancia.setBackground(new java.awt.Color(255, 255, 255));

        jtabla.setBackground(new java.awt.Color(204, 204, 204));
        jtabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153)));
        jtabla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtabla.setForeground(new java.awt.Color(0, 0, 0));
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Estrella", "Velocidad", "Distancia", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtabla);

        bcomenzar.setBackground(new java.awt.Color(204, 204, 204));
        bcomenzar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bcomenzar.setForeground(new java.awt.Color(0, 0, 0));
        bcomenzar.setText("C O M E N Z A R");
        bcomenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcomenzarMouseClicked(evt);
            }
        });

        bpausa.setBackground(new java.awt.Color(204, 204, 204));
        bpausa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bpausa.setForeground(new java.awt.Color(0, 0, 0));
        bpausa.setText("P A U S A R");
        bpausa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bpausaMouseClicked(evt);
            }
        });

        bagregar.setBackground(new java.awt.Color(204, 204, 204));
        bagregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bagregar.setForeground(new java.awt.Color(0, 0, 0));
        bagregar.setText("A G R E G A R");
        bagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bagregarMouseClicked(evt);
            }
        });

        cbplayer.setBackground(new java.awt.Color(255, 255, 255));
        cbplayer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbplayer.setForeground(new java.awt.Color(0, 0, 0));

        cbstar.setBackground(new java.awt.Color(255, 255, 255));
        cbstar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbstar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Partida");

        jpartida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jpartida.setForeground(new java.awt.Color(0, 0, 0));
        jpartida.setText("+++++++");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jugador");

        jjugador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jjugador.setForeground(new java.awt.Color(0, 0, 0));
        jjugador.setText("+++++++");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estrella");

        jestrella.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jestrella.setForeground(new java.awt.Color(0, 0, 0));
        jestrella.setText("+++++++");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Distancia Recorrida");

        jdistanciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jdistanciar.setForeground(new java.awt.Color(0, 0, 0));
        jdistanciar.setText("+++++++");

        jdistanciat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jdistanciat.setForeground(new java.awt.Color(0, 0, 0));
        jdistanciat.setText("+++++++");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Distancia total");

        jmensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jmensaje.setForeground(new java.awt.Color(102, 0, 51));
        jmensaje.setText("*MENSAJE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(bagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(cbstar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpbdistancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bcomenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bpausa, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jpartida)
                                .addGap(166, 166, 166)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jdistanciar)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jjugador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jestrella)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jdistanciat)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jmensaje)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpartida)
                    .addComponent(jLabel4)
                    .addComponent(jjugador)
                    .addComponent(jLabel6)
                    .addComponent(jestrella))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jdistanciar)
                    .addComponent(jLabel11)
                    .addComponent(jdistanciat))
                .addGap(26, 26, 26)
                .addComponent(jmensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpbdistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcomenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpausa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbstar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcomenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcomenzarMouseClicked
        // TODO add your handling code here:
        t.start();
        l.start();
    }//GEN-LAST:event_bcomenzarMouseClicked

    private void bpausaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpausaMouseClicked
        // TODO add your handling code here:
        if(t.isAvanzar() == true)
        {
            t.setAvanzar(false);
            bpausa.setText("C O N T I N U A R");
        }
        else if(!t.isAvanzar())
        {
            t.setAvanzar(true);
            bpausa.setText("P A U S A R");
        }
    }//GEN-LAST:event_bpausaMouseClicked

    private void bagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagregarMouseClicked
        // TODO add your handling code here:
        try
        {
            DefaultTableModel tabla = (DefaultTableModel) jtabla.getModel();
            tabla.addRow(new Object[]{
                (String)cbplayer.getSelectedItem(), 
                (String)cbstar.getSelectedItem(),
                bdd.getVelocidadJugador((String)cbplayer.getSelectedItem()),
                bdd.getDistanciaEstrella((String)cbstar.getSelectedItem()),
                "En espera"});
        } catch (IOException e) {
            jmensaje.setText("ERROR DE LECTURA/ESCRITURA DE DATOS");
        }
    }//GEN-LAST:event_bagregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bcomenzar;
    private javax.swing.JButton bpausa;
    private javax.swing.JComboBox<String> cbplayer;
    private javax.swing.JComboBox<String> cbstar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jdistanciar;
    private javax.swing.JLabel jdistanciat;
    private javax.swing.JLabel jestrella;
    private javax.swing.JLabel jjugador;
    private javax.swing.JLabel jmensaje;
    private javax.swing.JLabel jpartida;
    private javax.swing.JProgressBar jpbdistancia;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables
}
